name: re_dice
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shake_detector: ^0.1.2
  dotted_border: ^2.1.0
  # shake_gesture: ^1.1.0

  objectbox: ^4.2.0
  objectbox_flutter_libs: any
  path: any
  path_provider: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  objectbox_generator: any
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
